let catagories = [
    {id: 1, catName: "Korey Gas", amount: "0"},
    {id: 2, catName: "Jennifer Gas", amount: "0"},
    {id: 3, catName: "Kolton Gas", amount: "0"},
    {id: 4, catName: "Dana Gas", amount: "0"},
    {id: 5, catName: "Gerry Gas", amount: "0"},
    {id: 6, catName: "Irene Gas", amount: "0"},
    {id: 7, catName: "EZ-PASS", amount: "0"},
    {id: 8, catName: "Travel", amount: "0"},
    {id: 9, catName: "Meals", amount: "0"},
    {id: 10, catName: "Office Supplies", amount: "0"},
    {id: 11, catName: "Mobile Phones", amount: "0"},
    {id: 12, catName: "Waste Disposal", amount: "0"},
    {id: 13, catName: "Materials-Misc", amount: "0"},
    {id: 14, catName: "Office Phones", amount: "0"},
    {id: 15, catName: "Medical", amount: "0"},
    {id: 16, catName: "Materials-Roofing", amount: "0"},
    {id: 17, catName: "Accounting", amount: "0"},
    {id: 18, catName: "Dues & Subscriptions", amount: "0"},
    {id: 19, catName: "Vehical Maint", amount: "0"},
    {id: 20, catName: "Vehical Insurance", amount: "0"},
    {id: 21, catName: "Vehical Registration", amount: "0"},
    {id: 22, catName: "Advertising", amount: "0"},
    {id: 23, catName: "Misc", amount: "0"},
    {id: 24, catName: "Credit Card Fees", amount: "0"},
    {id: 25, catName: "Internet", amount: "0"},
    {id: 26, catName: "Tools & Equipment", amount: "0"},
    {id: 27, catName: "Building Maint & Upkeep", amount: "0"},
    {id: 28, catName: "Subcontractor-Gutters", amount: "0"},
    {id: 29, catName: "Materials-Windows", amount: "0"},
    {id: 30, catName: "Materials-Siding", amount: "0"}
]

module.exports =  catagories